kind: pipeline
type: docker
name: api-six-deploy


steps:
  - name: deploy-with-compose
    image: docker/compose:debian-1.29.2  # 使用 docker-compose 官方镜像
    pull: never
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
      - name: ssh-cache
        path: /root/.ssh
      - name: app-cache
        path: /app
    commands:
      - rm -rf /app/*
      - cp -r ./* /app
      # 切换到项目目录（假设代码库已克隆到 /app）
      - cd /app
      - ls -la
      # 启动服务（强制重建镜像）
      - docker-compose down
      - docker-compose up -d --build --force-recreate
    environment:
#       传递 Nacos 认证信息（如果注册服务时需要）
      NACOS_USERNAME:
        from_secret: NACOS_USERNAME
      NACOS_PASSWORD:
        from_secret: NACOS_PASSWORD

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock  # 挂载宿主机的 Docker Socket
  - name: ssh-cache
    host:
      path: /home/asialjim/.ssh
  - name: app-cache
    host:
      path: /vol2/1000/docker/api/gateway