kind: pipeline
type: docker # 定义流水线类型，还有kubernetes、exec、ssh等类型
name: api-six-deploy


steps:
  - name: build-start
    image: drone/drone-runner-ssh:lasted # SSH工具镜像
    pull: never
    settings:
      host:
        from_secret: ssh_host # 从 secret 中读取宿主机ip地址
      username:
        from_secret: ssh_username # 从Secret中读取SSH用户名
      password:
        from_secret: ssh_password # 从Secret中读取SSH密码
      port: 22 # 远程连接端口
    commands:
      - cp -r ./* /app
      - cd /app
      - docker-compose down
      - docker-compose up -d --build --force-recreate

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock  # 挂载宿主机的 Docker Socket
  - name: ssh-cache
    host:
      path: /home/asialjim/.ssh