
knife4j:
  gateway:
    enabled: true
    tags-sorter: order
    operations-sorter: order
    strategy: discover
    discover:
      enabled: true
      version: openapi3
      oas3:
        url: /v3/api-docs?group=default
        validator-url:
        oauth2-redirect-url:
    basic:
      enable: on
      username: gateway
      password: gateway

server:
  port: ${gateway_port:80}

spring:
  application:
    name: Gateway
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos_server:'http://192.168.101.200:8848'}
        namespace: ${nacos_namespace:public}
        username: ${nacos_username:nacos}
        password: ${nacos_password:nacos}
        group: ${nacos_group:DEFAULT_GROUP}
    loadbalancer:
      retry:
        backoff:
          enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
